language: cpp
compiler: gcc

jobs:
  include:
  - os: linux
    dist: bionic
    name: Ubuntu 18.04
    env:
    - TARGET=linux
    - OUTPUT_DIRS="lib share"
    addons:
      apt:
        packages:
        - g++
        - libgfortran3
        - gfortran
        - make
        - python3.8
        - python3-venv
        - python3-pip
    cache:
    - pip
  - os: linux
    name: manylinux2010
    services:
    - docker
    env:
    - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
    - PLAT=manylinux2010_x86_64
    - TARGET=manylinux2010
    - OUTPUT_DIRS=build
    install:
    - docker pull $DOCKER_IMAGE
    - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD "cd /io && /io/travis/build.sh"
    before_script: skip
    script: ls build/
  - os: osx
    name: OSX
    env:
    - TARGET=osx
    - FORTRAN_DIR="/usr/local/gfortran/lib/"
    - LDFLAGS="-L$FORTRAN_DIR"
    - OUTPUT_DIRS="lib share"
    addons:
      homebrew:
        update: true
        packages:
        - python@3.8
        - gcc
        - make
        - automake
        - autoconf
        - libtool
        - ccache
        casks:
        - gfortran
    before_cache:
    - brew cleanup
    cache:
      - pip
      - ccache
      - directories:
        - $HOME/Library/Caches/Homebrew
    before_install:
    - export PATH="/usr/local/opt/ccache/libexec:$PATH"
    - ls $FORTRAN_DIR
    - alias python3="/usr/local/opt/python@3.8/bin/python3"
    - alias pip3="/usr/local/opt/python@3.8/bin/pip3"
  - os: linux
    dist: bionic
    name: Windows64
    env:
    - TARGET=win64
    - FORTRAN_DIR="$(x86_64-w64-mingw32-gfortran --print-file-name=)"
    - LDFLAGS="-L$FORTRAN_DIR"
    - CXX=x86_64-w64-mingw32-gcc
    - F77=x86_64-w64-mingw32-gfortran
    - CONFIG_FLAGS="--build=x86_64-pc-linux-gnu --host=x86_64-w64-mingw32"
    - OUTPUT_DIRS="bin share"
    addons:
          apt:
            packages:
            - g++
            - gfortran
            - make
            - libtool
            - mingw-w64
            - mingw-w64-tools
            - mingw-w64-common
            - gfortran-mingw-w64
            - gfortran-mingw-w64-x86-64
            - gcc-mingw-w64
            - gcc-mingw-w64-x86-64
            - g++-mingw-w64
            - g++-mingw-w64-x86-64
    # Skip testing for Windows target
    before_script: skip
    script: skip

install:
- ./bootstrap
- ./configure --prefix=$PWD $CONFIG_FLAGS
- make install
- ls $OUTPUT_DIRS

before_script:
- source ~/.bashrc
- python --version
- python3 --version
- pip3 install --upgrade pip
- pip3 install -r test/requirements.txt

script:
- python3 -m pytest

before_deploy:
- mkdir build
- tar -czvf build/smelib_$TARGET.tar.gz $OUTPUT_DIRS

deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  file_glob: true
  file: build/*
  api_key:
    secure: mVOwSNIG/LXshCZD4YzVKLKelp0qqSOzvHME+4huKHqDces3CSUIPLThvxk1/Uk3foKn1IiIcAsZaQ+LGieGCqi204nDDsjuLxuqSqoO5P9Q+Hqs81pfHV8hSMKcEGmpmzmTQt+RDBuSXyoGx8YC3d65JKyOEpgbpzScnWo79LLEYXopUnq5p2jKG15AoVWQTDbm9OnoItfic1iFwEG2KlHLEx4MOhHtn79Yhuxkya9O452s7xJu2EoC7VsN0u66bhp+NQ8/J2qCDNATRfUMCT5FMBLdK6DX0aoD3wxdXkiVYUUoev3Qw0WaqYwZwDos/1T2ttn+PGEkYe6jTKlMyiH2J9jeWjaRdV0dIKVdxMyS0cJpf6n32Lb3HQ+g9RcEXeywC4ZV5SXHfYTv3WlJcAmKmCktPS9ErQ3FmttcKT6xO1C7S2IQViXE1Q/Ml7go9+hUzMNvJLxfW2O1TjmeS/uspK5a5Ln+/f4qQx70h87Cf25kNsFrLPxakgcV/I+giMALa2ilWODhbpGRC/PdO3M/LUxVtenz0jgczq//S9uvMLHt0qDP5IXVVQIUJ6tzT+UAyOCEh4HRYP5wIRpHwqA4xyWcAvgRXIGT1K/fLDuxl2VENmVY9H1H7Keh3kKdf77nA+T/6bIiig7+0jt9LVDKrTqKektGLghaahOQSTM=
  on:
    tags: true