language: c
compiler: gcc

jobs:
  include:
    - os: linux
      before_install:
        - sudo apt-get install gfortran
    - os: osx
      before_install:
        - brew reinstall libtool
    - os: windows
      before_install:
        - choco install cygwin
        - C:\\tools\\cygwin\\cygwinsetup.exe -q -P make,unzip,automake,autoconf,zip,libtool

install:
  - ./bootstrap

script:
  - ./configure
  - make
