language: c
compiler: gcc

jobs:
  include:
    - os: linux
      before_install:
        - sudo apt-get install gfortran
    - os: osx
      before_install:
        - brew install libtool
    - os: windows
      before_install:
        - |-
              [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
              choco upgrade --no-progress -y msys2
              taskkill //IM gpg-agent.exe //F
              ;;
      before_cache:
        - |-
              $msys2 pacman --sync --clean --noconfirm
              ;;
      cache:
          directories:
          - $HOME/AppData/Local/Temp/chocolatey
          - /C/tools/msys64


install:
  - ./bootstrap

script:
  - ./configure
  - make
