language: c
compiler: gcc

jobs:
  include:
    - os: linux
      before_install:
        - sudo apt-get install gfortran
    - os: osx
      before_install:
        - brew reinstall libtool
    - os: windows
      before_install:
        - choco install -y mingw
        - apt-get install gfortran

install:
  - ./bootstrap

script:
  - ./configure
  - make
