language: cpp
compiler: gcc
env:
- SHELL=
jobs:
  include:
  - os: linux
    addons:
      apt:
        packages:
        - g++
        - gfortran
        - make
  - os: osx
    addons:
      homebrew:
        update: true
        packages:
        - make
        - automake
        - libtool
    before_cache:
    - brew cleanup
  - os: windows
    env:
    - SHELL=$msys2
    before_install:
    - |-
      case $TRAVIS_OS_NAME in
        windows)
          [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
          choco uninstall -y mingw
          choco upgrade --no-progress -y msys2
          export msys2='cmd //C RefreshEnv.cmd '
          export msys2+='& set MSYS=winsymlinks:nativestrict '
          export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
          export mingw64="$msys2 -mingw64 -full-path -here -c \$\* --"
          export msys2+=" -msys2 -c \$\* --"
          $msys2 pacman --sync --noconfirm --needed \
                  autoconf \
                  automake \
                  libtool \
                  mingw-w64-x86_64-libtool \
                  mingw-w64-x86_64-toolchain
          ## Install more MSYS2 packages from https://packages.msys2.org/base here
          taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
          export PATH=/C/tools/msys64/mingw64/bin:$PATH
          export MAKE=mingw32-make  # so that Autotools can find it
          ;;
      esac
    before_cache:
    - |-
      case $TRAVIS_OS_NAME in
        windows)
          # https://unix.stackexchange.com/a/137322/107554
          $msys2 pacman --sync --clean --noconfirm
          ;;
      esac
    cache:
      directories:
      - "$HOME/AppData/Local/Temp/chocolatey"
      - "/C/tools/msys64"
install:
- "$SHELL mkdir m4"
- "$SHELL ./bootstrap"
script:
- "$SHELL ./configure --prefix=$PWD"
- "$SHELL make install"
- "$SHELL tar -czvf smelib.tar.gz lib share"

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "AWehrhahn"
  - git config --local user.email "ansgar.wehrhahn@physics.uu.se"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key:
    secure: wUapDibGNiNKwuHW3fDylBMsXzb2gmo9lXR7HvLNev1fT3mwF0FHU6FsG4FDuT/dcND26YkB+laKQHGlkgXuIIsiaKdEaGr7D8BXTk3gQywbYz7TGIR+n02aswXy93P276uky/2ZQ1fdyrv9YrIXIep5O8lDggSSo25PevcAtLKUTqAyFlSeaPqRQjLXSQZT66Kx4vdkNWgLYzNoHxCFBobRKqXG68AaCzPIfnwcsPau3lH4G75mvXZa+ESCZeble4JkSbB/rcJ5w88mfEYfvDhbT9H6gq4RJNsetjjJNJQq04FJkLfXOg2POpOMTnZP9v4i4P6gLrLyLlIfqfl00AxAGqsghDGV9/wpuvi3gw4+/HyRcuLse42JruKVbf2hb4OnoQCDB92nXcbQO4o2Bu256PkFbqsBEj0v9ja0O/ubPqXcm5Ph5+qvmP49LDC1qzJN0UyVwF6eu3IoFTWCbARlfQFs2fWmAKdpHiiO61lRD/hFLhn2ThRbYA/tnJfJKHgnkDdNNr9cSaLgKD0FQKugyg+T1eLa+k6FuGUJJxq2Wo28GBAYF+ihGwAMmCSpU3uH3+XE1ceqUQWxSw88GH6uKoAMlgaLgryMXDr5lLctE8LfiJyeKyZFrC21VbBmDzhjLWqai2ma1PL9w38OsFaHUzJiA9bJKLf/GOlK5Nk=
  file: smelib.tar.gz
  on:
    repo: AWehrhahn/SMElib
