language: c
compiler: gcc

jobs:
  include:
    - os: linux
      before_install:
        - sudo apt-get install gfortran
    - os: osx
      before_install:
        - brew reinstall libtool
    - os: windows

install:
  - ./bootstrap

script:
  - ./configure
  - make
