// define the external methods
const char *Cython_SMELibraryVersion();                                                                                                                                                                                                          /* Return SME library version */
const char *Cython_GetDataFiles();                                                                                                                                                                                                               /* Return the required data files */
const char *Cython_GetLibraryPath();                                                                                                                                                                                                             /* Return the current data file directory */
const char *Cython_SetLibraryPath(const char *path, int pathlen);                                                                                                                                                                                /* Set the data file directory */
const char *Cython_InputWaveRange(double wmin, double wmax);                                                                                                                                                                                     /* Read in Wavelength range */
const char *Cython_SetVWscale(double gamma6);                                                                                                                                                                                                    /* Set van der Waals scaling factor */
const char *Cython_SetH2broad();                                                                                                                                                                                                                 /* Set flag for H2 molecule */
const char *Cython_ClearH2broad();                                                                                                                                                                                                               /* Clear flag for H2 molecule */
const char *Cython_InputLineList(int nlines, int slen, const char *species, double *atomic);                                                                                                                                                     /* Read in line list */
const char *Cython_OutputLineList(int nlines, double *atomic);                                                                                                                                                                                   /* Return line list */
const char *Cython_UpdateLineList(short nlines, int slen, const char *species, double *atomic, short *index);                                                                                                                                    /* Change line list parameters */
const char *Cython_InputModel(short ndepth, double teff, double grav, double wlstd, const char *motype, int slen, short *opflag, double *depth, double *temp, double *xne, double *xna, double *rho, double *vt, double radius, double *height); /* Read in model atmosphere */
const char *Cython_InputDepartureCoefficients(double *bmat, int lineindex);
const char *Cython_GetDepartureCoefficients(double *bmat, int nrhox, int line);                                                                                                                                    /* Get NLTE b's for specific line */
const char *Cython_GetNLTEflags(short *nlte_flags, int nlines);                                                                                                                                                    /* Get line list NLTE flags */
const char *Cython_ResetDepartureCoefficients();                                                                                                                                                                   /* Reset LTE */
const char *Cython_InputAbund(double *abund);                                                                                                                                                                      /* Read in abundances */
const char *Cython_Opacity();                                                                                                                                                                                      /* Calculate opacities */
const char *Cython_GetOpacity(short ifop, short length, double *result, int slen, int klen, const char *species, const char *key);                                                                                 /* Returns specific cont. opacity */
const char *Cython_Ionization(short ion);                                                                                                                                                                          /* Perfrom EOS calculations */
const char *Cython_GetDensity(short length, double *result);                                                                                                                                                       /* Returns density in g/cm^3 */
const char *Cython_GetNatom(short length, double *result);                                                                                                                                                         /* Returns atomic number density */
const char *Cython_GetNelec(short length, double *result);                                                                                                                                                         /* Returns electron number density */
const char *Cython_Transf(short nmu, double *mu, double *cint_seg, double *cintr_seg, int nwmax, int nw, double *wint_seg, double *sint_seg, double accrt, double accwi, short keep_lineop, short long_continuum); /* Computes spectral synthesis */
const char *Cython_CentralDepth(int nmu, double *mu, int nwsize, float *table, double accrt);                                                                                                                      /* Computes line central depths */
const char *Cython_GetLineOpacity(double wave, short nrhox, double *lop, double *cop, double *scr, double *tsf, double *csf);                                                                                      /* Returns specific line opacity */
const char *Cython_GetLineRange(double *linerange, int nlines);                                                                                                                                                    /* Get validity range for every line */
