name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      run: apt-get install -Y f2c
    
    - name: Run F2C
      run: f2c -w -a -C++ -Nn1604 -Nq1200 -dsrc/eos/ src/eos/*.f & f2c -w -a -c++ -dsrc/sme/ src/sme/*.f
    
    - name: Replace Makefile.am
      run: rm makefile.am & mv makefile_f2c.am makefile.am
    
    - name: Run Bootstrap and Configure
      shell: bash
      run: ./bootstrap & /configure --prefix=$PWD
  
    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Build
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: make install
